export const FACE_SHEET = "Face and body";

export const QUIZ_OPTIONS = {
  skinTypes: ["Oily", "Dry", "Normal", "Combination"],
  sensitivityOptions: ["No", "Yes"],
  faceBodyConcerns: [
    "Acne",
    "Body Acne",
    "Dryness",
    "Open Pores",
    "Uneven Skin Tone",
    "Dark Spots/Pigmentation",
    "Melasma",
    "Barrier Repair",
    "Comedones",
    "Wrinkles/Fine lines",
    "Redness/Irritation",
    "Dehydration",
    "Dullness",
    "Tanning",
  ],
  lipsEyesConcerns: [],
  specialConditions: ["Excessive Dryness", "Pregnant", "Breastfeeding", "None"],
  ages: ["Below 16", "16-24", "25-34", "35-44", "Above 45"],
  genders: ["male", "female", "other", "prefer not to say"],
};

// The catalog only carries three age-fit score columns (<16, 17-25, Above 25),
// so the finer 25-34 / 35-44 / Above 45 bands all read off the same "+>25"
// column — the quiz asks a more specific question than the data can answer,
// but grouping them keeps scoring correct while giving a friendlier picker.
// "teen"/"adult" stay mapped for profiles saved before this change.
export const AGE_COLUMNS = {
  teen: ["<16"],
  "under 16": ["<16"],
  "below 16": ["<16"],
  "<16": ["<16"],
  "16": ["<16"],
  adult: ["17-25", "+>25"],
  "16 24": ["17-25"],
  "17-25": ["17-25"],
  "17 25": ["17-25"],
  "25 34": ["+>25"],
  "35 44": ["+>25"],
  "above 45": ["+>25"],
  "above 25": ["+>25"],
  "over 25": ["+>25"],
  "25+": ["+>25"],
  "+>25": ["+>25"],
};

export const CONCERN_COLUMNS = {
  acne: ["Acne"],
  "body acne": ["Body Acne"],
  dryness: ["Dryness"],
  "open pores": ["Open Pores"],
  "large pores": ["Open Pores"],
  "uneven skin tone": ["Uneven Skin Tone"],
  "dark spots pigmentation": ["Dark Spots/Pigmentation"],
  "dark spots": ["Dark Spots/Pigmentation"],
  pigmentation: ["Dark Spots/Pigmentation"],
  melasma: ["Melasma"],
  "barrier repair": ["Barrier Repair"],
  comedones: ["Comedones"],
  "wrinkles fine lines": ["Wrinkles/Fine lines"],
  aging: ["Wrinkles/Fine lines"],
  "redness irritation": ["Redness/Irritation"],
  sensitivity: ["Redness/Irritation"],
  dehydration: ["Dehydration"],
  dullness: ["Dullness"],
  tanning: ["Tanning"],
};

export const SCORE_COLUMNS = [
  "<16",
  "17-25",
  "Above 25",
  "Acne",
  "Body Acne",
  "Dryness",
  "Open Pores",
  "Uneven Skin Tone",
  "Dark Spots/Pigmentation",
  "Melasma",
  "Barrier Repair",
  "Comedones",
  "Wrinkles/Fine lines",
  "Redness/Irritation",
  "Dehydration",
  "Dullness",
  "Tanning",
  "Concern weight",
  "Oily Score",
  "Oily+Sensitive Score",
  "Dry Score",
  "Dry+Sensitive Score",
  "Normal Score",
  "Normal+Sensitive Score",
  "Combination Score",
  "Combination+Sensitive Score",
  "Excessive Dryness score",
  "Pregnancy Score",
  "Breastfeeling Score",
];

export const THRESHOLDS = [90, 80, 70, 60, 50];
