services:
  - type: web
    name: roopsee-product-coverage-service
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api.index:app --bind 0.0.0.0:$PORT
    autoDeploy: true
    envVars:
      - key: HOST
        value: 0.0.0.0
